name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
      - feature/docs-ci
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Ensure docs folder exists
        run: mkdir -p docs

      - name: Ensure Doxyfile exists
        run: |
          if [ ! -f docs/Doxyfile ]; then
            doxygen -g docs/Doxyfile
            sed -i 's|OUTPUT_DIRECTORY       =|OUTPUT_DIRECTORY       = docs/html|' docs/Doxyfile
            sed -i 's|GENERATE_HTML          = NO|GENERATE_HTML          = YES|' docs/Doxyfile
          fi

      - name: Generate Documentation
        run: doxygen docs/Doxyfile

      - name: Debug - List generated files
        run: |
          echo "Listing docs/html directory:"
          ls -R docs/html || echo "Docs HTML directory not found!"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
